onnx/onnx-tensorrt

CMakeLists.txt

- Fixes issue where C2 unintentionally builds this as a shared lib
and then can't find it at runtime.

Ensure libnvonnxparser_plugin is always static

---

ImporterContext.hpp
onnx2trt_common.hpp
plugin.cpp
plugin.hpp

- Fixes bug where NvPlugin plugins are not correctly serialized and
cause a crash during deserialization.
- Serialization of the plugin type string is now done in an adapter
instead of a base class, which allows it to be used by the NvPlugin
adapter.
- Also cleans up a few minor things related to the plugin class
hierarchy.

Fix some issues with plugin type serialization

---

InstanceNormalization.cpp
InstanceNormalization.hpp

- Now runs in the requested precision (fp32 or fp16) instead of casting
fp32 to fp16.
- Also fixes getWorkspaceSize (no workspace is used).

Clean up and fix InstanceNorm plugin for fp32 IO

---

ImporterContext.hpp

Makes the opset check robust to missing opset field or renamed domain

Fix crash due to missing opset field in old models

---

README.md

This is a kinda hidden feature, but when you do that it displays tests names as they're being done instead of only at the end [so if segfault occurs you know which test caused it].

Add info about -v flag support in tests

---

setup.py

Needed before it is used in `onnx_tensorrt/tensorrt_engine.py`.

Add pycuda dependency to setup.py

---

TensorOrWeights.hpp
builtin_op_importers.cpp

- Refactors Add/Mul/Pow implementations into importScaleOp function.
- Changes all elementwise ops to use ElementWise + Constant layers
instead of Scale layer when building against TensorRT >= 4.
This improves support for broadcasting across any set of dimensions.
- Adds explicit handling of binary op broadcasting semantics for ONNX
opset < 7 (aka 'legacy broadcasting').

Refactor + improve handling of elwise broadcasting

---

FancyActivation.hpp
InstanceNormalization.hpp
ResizeNearest.hpp
Split.hpp
plugin.hpp

This reverts commit 07a9e59aaacdc9af799ee553f335baf81dee5bf3.
The TRT 5 GA release is backwards compatible with TRT 4, so this patch
is no longer needed.

Revert "Fix compilation with TensorRT 5 RC (#55)"

---

CMakeLists.txt

With TRT5 support integrated, I'd propose building with sm_75 by default.

Update GPU_ARCHS with 75

---

CMakeLists.txt

Cmake versions 3.10 and later have native support for CUDA, no need to treat
it differently.

Implemented support for Cmake versions >= 3.10

---

builtin_op_importers.cpp

Note that this change is dependent on https://github.com/onnx/onnx-tensorrt/pull/94/files for the convertToTensor helper function.

Updating unsqueeze op to work with non-tensor inputs

---

builtin_op_importers.cpp

Requires convertToTensor to be merged in first from https://github.com/onnx/onnx-tensorrt/pull/94.
This will replace this pull request https://github.com/onnx/onnx-tensorrt/pull/82 as the original author is no longer maintaining  thsi repo.

Implementing slice op

---

builtin_op_importers.cpp

Since we only support a constant scale factor PRELU is essentially a LeakyRelu. Removing it from the registry so that supportsModel() can correctly catch the fact that common uses of PRELU are not supported.

Commenting out PRELU op 

---

PluginFactory.cpp

Looks like its missed plugin wrapper in the PluginFactory. Because of this, the cuda engine cannot be serialized correctly.

wrap plugins for correct serialization

---

ShapedWeights.cpp
ShapedWeights.hpp
onnx2trt_utils.hpp

Downcast them to INT32 if possible, error out otherwise.

Support INT64 types in ShapedWeights

---

builtin_op_importers.cpp

Slice is not working with negative indexing, and seems to have some problems as it's also using the wrong dimensions of tensor for each index: `if (starts[i] == 0 && ends[i] >= dims.d[i])` instead of `if (starts[i] == 0 && ends[i] >= dims.d[axis])`
A little comment: updating onnx will require some rework here (starts and ends are Tensors in latest onnx) but would allow to use "steps".

fix slice for negative indexing

---

ShapedWeights.cpp

Hi there,
Fully connected conversion would fail if weights are fp16 because of the lack of support on transposeWeights.
This PR intend to add the support making fully connected fp16 weights loading possible. (Tested on MXNet-TRT)

Add transpose for 2d fp16 weights

---

builtin_op_importers.cpp

TRT 5.1 only supports FLOAT16->FLOAT32 casts in the identity layer.

Disable unsupported casts

---

builtin_op_importers.cpp

The axes_set is init before axes is corrected when inputs is a tensor.
Fixes #279

Fix a bug in ImportUnsqueeze function

---

onnx_utils.hpp

master build with error:
```
onnx_utils.hpp:135:34: error: ‘numeric_limits’ is not a member of ‘std’
std::numeric_limits<int>::max()/4);
```
which needs add an include to solve .
Test on gcc5, ubuntu16.04
after add include, build pass.

fix error:numeric_limits

---

CMakeLists.txt

This allows projects using this to specify c++14 or c++17 for their cuda files without it conflicting here.

Only set c++11 if not already specified

---

ModelImporter.cpp

Register all weight outputs as they may be used as an unused optional input for a child node.

Support empty weights

---

ModelImporter.cpp
builtin_op_importers.cpp

We encountered some warnings/errors when building Onnxruntime + TensorRT EP on Windows using Visual Studio 2019.
onnx-tensorrt advertises as a [C++11 project](https://github.com/onnx/onnx-tensorrt/blob/master/CMakeLists.txt#L25) 
so lambdas closure types aren't literals and can't be assigned to constexpr variable.
see https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019#lambda-closures
it is allowed in c++17, but not c++14/c++11
also fixed some [C4305 truncation build warnings](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4305?view=vs-2019)

fix some build warnings/errors on Windows VS2019

---

operators.md

There are two overlapping RNN operators, one supporting and the other not. Since onnx supports RNN, the one with supported N should be removed.
Signed-off-by: juhyung <sonju0427@gmail.com>

Fix typo in operators.md supported onnx operators

---

ImporterContext.hpp
ModelImporter.cpp
onnx2trt.hpp
onnx2trt_utils.cpp
onnx2trt_utils.hpp

* Added mUnsupportedShapeTensors member to ImporterContext to hold shape tensor names of any layer outputs that do not support it.
* Added helper function supportsShapeTensor to hold the list of what layers support and do not support shape tensor outputs. 
* Updated removeShapeTensorCasts function to call supportShapeTensor and populate mUnsupportedShapeTensors during it's initial loop to remove any casts
* Updated supportsModel() to filter out any nodes that have output tensors in mUnsupportedShapeTensors

Add check for shape tensor outputs

---

ModelImporter.cpp
onnx2trt_utils.hpp

Prefixes all logging messages from the parser with [TRT], and update some std::cout calls to use the logging API.

Prefix logging messages with [TRT]

---

README.md

Add local build instructions (#498)

---

ImporterContext.hpp

Signed-off-by: Tom Peters <thomas.d.peters@gmail.com>
This is the fix I described from #466

fix duplicate names bug in ImporterContext

---

builtin_op_importers.cpp

Support dynamic and 3D instanceNormalization

---

builtin_op_importers.cpp

Add restrictions on multi-input convolutions

---

builtin_op_importers.cpp

Update resize limitations in TensorRT

---

ImporterContext.hpp
ModelImporter.cpp
README.md
builtin_op_importers.cpp
onnx2trt_utils.hpp

Merge master changes for 7.1 to 7.1 branch.
Signed-off-by Kevin Chen kevinch@nvidia.com

Merge master changes -> 7.1

---

builtin_op_importers.cpp

Add constant weights for GEMMs to refitmap

---

ShapedWeights.cpp

Add 4D transpose for weights

---

ShapeTensor.hpp
builtin_op_importers.cpp
onnx2trt_utils.cpp
onnx2trt_utils.hpp

Fix slice computations for starts and ends for large slices

---

builtin_op_importers.cpp
onnx2trt_utils.cpp
onnx2trt_utils.hpp

- The batchnorm importer wasn't handling cases where the input is 2D.
- Additionally, the scaleHelper was assuming static dimensions when attempting to unsqueeze/squeeze.
The fix comprises two parts:
1. Make scaleHelper unsqueeze 2D inputs to 4D
1. Update squeezing/unsqueezing logic to work with dynamic dimensions

Fixes batchnorm importer in non-4D/5D cases

---

builtin_op_importers.cpp
operators.md

Add reversesequence importer function

---

Dockerfile

This is a small fix to make the Dockerfile work with TensorRT 5.1. Since it's a version still commonly used (e.g. by DeepStream), I thought it would be worth keeping it working.

Update Dockerfile to work for TRT5.1

---

builtin_op_importers.cpp

Remove std::move in return to resolve this build failure:
[ 66%] Building CXX object CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/activation/activations.cc.o
/workspace/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘std::vector<nvinfer1::PluginField> onnx2trt::{anonymous}::loadFields(string_map<std::vector<unsigned char> >&, const OnnxAttrs&, const nvinfer1::PluginFieldCollection*)’:
/workspace/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:3737:21: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
3737 |     return std::move(fields);
|            ~~~~~~~~~^~~~~~~~
/workspace/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:3737 …

    Fix build on Ubuntu 20.04

---

builtin_op_importers.cpp
onnx2trt_utils.cpp

Fixes:
- #542 - set the path as the same directory as the file for relative-path weight imports
- #543 - set the name of the loop instead of first stateVar 

Fix external weights relative path and loop import

---

builtin_op_importers.cpp
onnx2trt_utils.cpp
onnx2trt_utils.hpp

Fixes #534 by casting BOOL tensors in concat nodes to INT32 first, then casting back.

Cast BOOL concats to INT32

---

ModelImporter.cpp
ModelImporter.hpp
NvOnnxParser.h
OnnxAttrs.hpp
onnx2trt_utils.cpp

* Added optional `model_path` parameter for `parse()` and `supportsModel()` API calls for importing models with external weights through ONNXRT
* Changed `file` to `path` for more complete logging
* Removed incorrect `const` qualifier in the attribute `type()` function

Update APIs with model_path for ONNXRT

---

builtin_op_importers.cpp

Fix loop naming and avoid registering trip limit tensor twice

---

CMakeLists.txt
README.md

Add library-only build target

---

builtin_op_importers.cpp
onnx2trt_utils.cpp
onnx2trt_utils.hpp

Update gather elements implementation

---

builtin_op_importers.cpp

Support optional plugin fields

---

CMakeLists.txt
README.md
builtin_op_importers.cpp
onnx2trt_utils.cpp

* Make the changes introduced in #678 optional with a CMake switch
* Optimize negative indices calculation

Mark negative indices support for gather as optional

---

README.md
builtin_op_importers.cpp
docs/Changelog.md
docs/operators.md

- Added support for InstanceNormalization on 5D tensors
- Added library only build target [#659](https://github.com/onnx/onnx-tensorrt/pull/659)
- Added support for negative gather indices [#681](https://github.com/onnx/onnx-tensorrt/pull/681)
- Added support for `DOUBLE`-typed inputs and weights through downcast to float [#674](https://github.com/onnx/onnx-tensorrt/pull/674)
- Added support for optional plugin fields in FallbackPlugin path [#676](https://github.com/onnx/onnx-tensorrt/pull/676)
- Updated license [#657](https://github.com/onnx/onnx-tensorrt/pull/657)
- Fixed index offset calculation in GatherElements [#675](https://github.com/onnx/onnx-tensorrt/pull/675)
- Clarified dynamic shape support for ReverseSequence

21.05 Release

---

builtin_op_importers.cpp
onnx2trt_utils.cpp

- Updates dropout mask tensor for opset < 12
- Adds boolean type assertion for GatherElements
- Adds ASSERTION for If subgraphs to have different output tensor names
- Fixes resize assertion
- Fixes Padding calculation for input tensors < 4D.

Fixes for ONNXRT unit tests

---

ModelImporter.cpp
onnx_utils.hpp

Allow onnx-tensorrt to build with protobuf version >= 3.11

support protobuf >= 3.11

---

onnx2trt_utils.cpp

Use shape tensor semantics to do the index conversion in order to support dynamic shapes

Fix dynamic argmax/min when select_last_index is set

---

builtin_op_importers.cpp
trt_utils.hpp

Address #824 
Since inputs are guaranteed to be 2D, no longer need to squeeze / unsqueeze inputs.

Fix GEMM importer

---

onnx_tensorrt/backend.py

Check if the output type of `libcudart.cudaGetErrorString(ret)` is bytes.
If so, decode it into `string` type.

Bug fix: decode error_string if necessary.

---

CMakeLists.txt
ConditionalHelpers.cpp
ConditionalHelpers.hpp
ImporterContext.cpp
ImporterContext.hpp
ModelImporter.cpp
ModelImporter.hpp
NvOnnxParser.h
README.md
TensorOrWeights.hpp
builtin_op_importers.cpp
docs/Changelog.md
docs/operators.md
onnx2trt.hpp
onnx2trt_utils.cpp
onnx2trt_utils.hpp
trt_utils.hpp

For more details, see the 8.6 EA release notes for new features added in TensorRT 8.6.
- Added support for `GroupNormalization`, `LayerNormalization`, `IsInf` operations
- Added support for INT32 input types for `Argmin`, `Argmax`, and `TopK`
- Added support for `ReverseSequence` operators with dynamic shapes
- Added support for `TopK` operators with dynamic `K` values
- Added `OnnxParserFlag` enum and `setFlag` interfaces to the ONNX parser to modify the default parsing behavior
- Added metadata tracking, now ONNX node metadata will be embedded into TensorRT layers
- All cast operations will now use the new `CastLayer` over the pervious `IdentityLayer`.

ONNX-TensorRT 8.6-EA release

---

CMakeLists.txt
ConditionalHelpers.cpp
ConditionalHelpers.hpp
ImporterContext.hpp
ModelImporter.cpp
OnnxAttrs.cpp
OnnxAttrs.hpp
builtin_op_importers.cpp
docs/Changelog.md
docs/operators.md
onnx2trt.hpp
onnx2trt_utils.cpp
onnx2trt_utils.hpp
onnx_tensorrt/__init__.py

For more details, see the 9.0 GA release notes for the fixes since 9.0 EA.
- Added support for FP8 and BF16 datatypes.
- Fixed a bug that previously caused `If` nodes to fail import due to branch output size mismatch
- Improved support for importing ONNX Local Functions
- Updated operator documentation

ONNX-TensorRT 9.0 GA Update

---

ImporterContext.hpp

"onnx/common/stl_backports.h" is deprecated, and the project supports C++14.

Use std::make_unique instead of one imported from ONNX

---

CMakeLists.txt
README.md
builtin_op_importers.cpp
docs/Changelog.md
docs/operators.md
onnx2trt_utils.cpp

For more details, see the 9.3 GA release notes for the fixes since 9.2 GA.
- Added native support for `INT32` and `INT64` types for `ArgMin` and `ArgMax` nodes
- Fixed check for valid `zero_point` values in `QuantizeLinear` and `DequantizeLinear` nodes

ONNX-TensorRT 9.3 Release

---

CMakeLists.txt
onnx2trt_utils.cpp

Normalize external weight paths, and update C++ build version to C++17 in line with ONNX 1.16.

Normalize external weights paths
