onnx/onnx-tensorrt

- ModelImporter.cpp
- builtin_op_importers.cpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
- onnx_backend_test.py
- onnx_tensorrt/backend.py
- onnx_tensorrt/tensorrt_engine.py
- trt_utils.hpp
Expands op support by integrating new features and capabilities available in TensorRT 4.
> TensorRT 4 feature support

- builtin_op_importers.cpp
To fix https://github.com/onnx/onnx-tensorrt/issues/24
> Remove broadcast check for opset ver >= 7

- CMakeLists.txt
- ModelImporter.cpp
- ModelImporter.hpp
- NvOnnxParser.h
- main.cpp
- onnx2trt_utils.hpp
- onnx_trt_backend.cpp
This PR implements the interface in `onnx/onnxifi.h`.
> TensorRT ONNXIFI interface

- ModelImporter.cpp
- onnx_trt_backend.cpp
Fix some bugs flushed by integration tests.
> Bug fix for ONNXIFI-TRT

- onnx_trt_backend.cpp
Didn't test, not sure if would even compile
> Refactor onnxGetBackendInfo

- FancyActivation.hpp
- InstanceNormalization.hpp
- ResizeNearest.hpp
- Split.hpp
- plugin.hpp
- Adds required clone() and getPluginVersion() methods to plugin
classes.
> Fix compilation with TensorRT 5 RC

- onnx2trt.hpp
- This allows building with GCC 7.
> Add missing include <functional>

- builtin_op_importers.cpp
Starting from opver 9, ONNX `Upsample` begin to use an extra input as `scale` instead of attributes (https://github.com/onnx/onnx/pull/1467). This PR adds support to that and tries to resolve https://github.com/onnx/onnx-tensorrt/issues/77.
> Add support for Upsample with opset_ver >= 9

- builtin_op_importers.cpp
Example shapes:
Softmax on (1000) on axis 0 should retain its shape
Softmax on (10,1000) on axis 0 should retain its shape (before it was reshaping it to (10000,1)
Softmax on (10,1000) on axis 1 should reshape to (1000,10)
> Fixing softmax for axis > 0

- onnx_tensorrt/backend.py
I think that shouldn't be there, please correct me if I'm wrong
> Remove pdb.set_trace() introduced in 448da819

- builtin_op_importers.cpp
For transposes that do not shuffle data around, correctly reshape it.
> Updating transpose to support "reshape" ops

- builtin_op_importers.cpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
Affected operators:
Convolution
Deconvolution
Averagepool
Maxpool
> Add padding mode option for layers

- builtin_op_importers.cpp
Remove TRT < 4 checks for elementwise ops.
Use convert_axis to check for axis 0.
> Cleaning up functions

- builtin_op_importers.cpp
Everything is in the title, just tested it on MXNet-TRT integration and everything is fine after this little fix.
> Correct a typo added on last commit

- builtin_op_importers.cpp
- We support both weight and tensor inputs through the convertToTensor utility function, these assertions can be removed.
> Remove input.is_tensor() assertions

- builtin_op_importers.cpp
- onnx2trt_utils.hpp
- Moved some helper functions to `onnx2trt_utils.hpp`
> Add broadcasting check for GEMM op

- ImporterContext.hpp
- ModelImporter.cpp
- ModelImporter.hpp
- builtin_op_importers.cpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
Use TRT 6.0's new shape tensor API to support dynamic shapes across all dimensions
Updated operators and helper functions:
* Reshape
* Squeeze
* Unsqueeze
Removed some assertions that do not hold when dealing with dynamic shapes.
> Improving dynamic shape support

- builtin_op_importers.cpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
* Added 3D support for global max and global average pooling
* Moved average pooling and max pooling to a generic function to reduce code duplication
> Update pooling operator importers 

- onnx2trt_utils.cpp
This change was missing. It is important to the webinar sample.
Signed-off-by: Anurag Dixit <a.dixit91@gmail.com>
> Namespace fix for TRT plugin

- CMakeLists.txt
- README.md
- common.hpp
- main.cpp
* New command line options.
* Updated documentation.
* Currently requires linking against onnx project.
> Added optimization only mode which runs optimization passes on the model without converting it to tensorrt.

- builtin_op_importers.cpp
* Fix logic on how to handle outputPadding values in ConvTranspose nodes
* Remove clamping value for epsilon in InstanceNormalization
> Fix deconv importer and remote instancenormalization epsilon clamp value

- builtin_op_importers.cpp
Add 1 to sizes if the negative slice is across the entire axis.
> Support negative slicing across an entire axis

- README.md
> Add local build instructions

- common.hpp
added noexcept specifier to TRT_Logger::log to avoid looser throw specifier error
> added noexcept specifier to TRT_Logger::log to avoid error

- builtin_op_importers.cpp
> Remove incorrect assertion from conv importer

- ModelImporter.cpp
> Fix return in parseFromFile

- ModelImporter.cpp
- onnx2trt_utils.hpp
Addresses #526 
Also reduce amount of console spew for `INFO` and `VERBOSE` level messages.
> Updating cout logging to use TRT logger

- ModelImporter.cpp
- ModelImporter.hpp
- NvOnnxParser.h
- onnx2trt_utils.cpp
Cherry-picked for the 7.1 branch from #621
> Update APIs with model_path for ONNXRT

- builtin_op_importers.cpp
> Fix build on Ubuntu 20.04

- builtin_op_importers.cpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
> Perform weights datatype check for slice

- ModelImporter.cpp
> Fix tracking of unsupported shape-tensor producing layers

- docs/contributing.md
Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>
> Add DCO to onnx-tensorrt repo

- docs/operators.md
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
> Add support for importing double-typed weights as float

- CMakeLists.txt
- README.md
cherry-pick PR659 to 7.1 branch
> Cherry-Pick to 7.1 branch: Add library-only build target (#659) 

- builtin_op_importers.cpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
> Support gather with negative indices

- builtin_op_importers.cpp
> Add dynamic shape assertion for CumSum

- ModelImporter.cpp
> Mark experimental ops as unsupported

- onnx_utils.hpp
> Support empty ONNX dimensions

- builtin_op_importers.cpp
> Mark BOOL tiles as unsupported

- builtin_op_importers.cpp
> Add support for INT32 and dynamic clips through elementwise

- ShapeTensor.cpp
> Fix shape tensor unsqueeze

- CMakeLists.txt
- ImporterContext.hpp
- ModelImporter.cpp
- onnx_tensorrt/__init__.py
Also includes misc fixes:
- Update onnx_tensorrt backend version to 8.0
- Adds ONNX2TRT version variable to CMake
> Remove unnecessary shape tensor checks

- builtin_op_importers.cpp
> Fix opset10 resizes

- builtin_op_importers.cpp
> Update QDQ axis assertion

- docs/operators.md
> Update RNN documentation

- CMakeLists.txt
- ConditionalHelpers.cpp
- ConditionalHelpers.hpp
- ImporterContext.hpp
- ModelImporter.cpp
- ModelImporter.hpp
- README.md
- ShapedWeights.cpp
- Status.hpp
- builtin_op_importers.cpp
- docs/Changelog.md
- docs/contributing.md
- docs/operators.md
- onnx2trt.hpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
- onnx_tensorrt/__init__.py
- onnx_utils.hpp
> TensorRT 8.2 EA ONNX Parser Release

- builtin_op_importers.cpp
> Fix nbDims build issue

- CMakeLists.txt
- ImporterContext.hpp
- ModelImporter.cpp
- README.md
- builtin_op_importers.cpp
- docs/Changelog.md
- docs/operators.md
- onnx2trt.hpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
- onnx_tensorrt/__init__.py
See the [changelog ](https://github.com/onnx/onnx-tensorrt/blob/master/docs/Changelog.md) for the full list of changes.
> TensorRT 8.2 ONNX Parser Release

- ModelImporter.cpp
> Add TRT plugins to supported ops list

- ConditionalHelpers.cpp
- ConditionalHelpers.hpp
- README.md
- builtin_op_importers.cpp
- docs/Changelog.md
> 22.02 onnx-TensorRT release

- builtin_op_importers.cpp
> Update where conditional

- ModelImporter.cpp
- common.hpp
the last PR missed other calls to SetTotalBytesLimit()
> missed other sections for supporting >= protobuf 3.11

- README.md
- docs/faq.md
- docs/operators.md
> Update REAMDEs to reflect master -> main rename

- ModelImporter.cpp
> Add support for DisentangledAttentionPlugin

- LICENSE
- README.md
- onnx_tensorrt/__init__.py
Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>
> TensorRT 8.4.1.5 updates

- CMakeLists.txt
- ConditionalHelpers.cpp
- ConditionalHelpers.hpp
- ImporterContext.cpp
- ImporterContext.hpp
- LICENSE
- ModelImporter.cpp
- NvOnnxParser.h
- OnnxAttrs.cpp
- README.md
- ShapeTensor.cpp
- ShapeTensor.hpp
- ShapedWeights.cpp
- ShapedWeights.hpp
- TensorOrWeights.hpp
- builtin_op_importers.cpp
- docs/Changelog.md
- docs/operators.md
- half.h
- ieee_half.h
- onnx2trt.hpp
- onnx2trt_common.hpp
- onnx2trt_utils.cpp
- onnx2trt_utils.hpp
- onnx_tensorrt/__init__.py
- onnx_utils.hpp
Merging 8.4-GA branch into main.
For more information on the TensorRT 8.4 release, see the [TensorRT 8.4.1 GA release notes](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-1).
See the [changelog](https://github.com/onnx/onnx-tensorrt/blob/8.4-GA/docs/Changelog.md) for the full list of changes.
> TensorRT 8.4 GA ONNX Parser Release

- CMakeLists.txt
- README.md
- builtin_op_importers.cpp
- docs/Changelog.md
- docs/faq.md
- docs/operators.md
- onnx_tensorrt/__init__.py
See changelog for more details on changes.
> ONNX-TensorRT 22.08 release

- CMakeLists.txt
- README.md
- onnx_tensorrt/__init__.py
> Update TensorRT version to 8.4.3

- builtin_op_importers.cpp
> Do not import potential nulltensor for size input in Resize nodes

- CMakeLists.txt
- README.md
- builtin_op_importers.cpp
- common.hpp
- docs/Changelog.md
- docs/faq.md
- docs/operators.md
- onnx_tensorrt/__init__.py
- onnx_tensorrt/backend.py
Mass merge `main` branch into `8.4-GA`
> Merge main 8.4

- docs/operators.md
> Mark Mod as supported

- docs/operators.md
> Mark OneHot and HardSwish as supported

- builtin_op_importers.cpp
> Check that QuantizeLinear is not UINT8 type

- builtin_op_importers.cpp
> Check that QuantizeLinear is not UINT8 type (#884)

- builtin_op_importers.cpp
- onnx2trt_utils.cpp
Signed-off-by: Yuan Yao <yuanyao@nvidia.com>
> Integrate 8.5.2.2 changes

- NvOnnxParser.h
- builtin_op_importers.cpp
Update enum name to be more descriptive of it's intended usage.
> Rename kVERSION_COMPATIBLE to kNATIVE_INSTANCENORM

- CMakeLists.txt
- ImporterContext.hpp
- ModelImporter.cpp
- ModelImporter.hpp
- ModelRefitter.cpp
- ModelRefitter.hpp
- NvOnnxParser.h
- README.md
- Status.hpp
- TensorOrWeights.hpp
- WeightsContext.cpp
- WeightsContext.hpp
- docs/Changelog.md
- docs/operators.md
- importerUtils.cpp
- importerUtils.hpp
- onnxOpImporters.cpp
- onnxProtoUtils.cpp
- onnxProtoUtils.hpp
- onnx_tensorrt/backend.py
- onnx_tensorrt/tensorrt_engine.py
For more details, see the 10.0 GA release notes.
- Added support for building with with `protobuf-lite`
- Fixed issue when parsing and refitting models with nested `BatchNormalization` nodes
- Added support for empty inputs in custom plugin nodes
> 10.0 GA Update
